### ISSUE TITLE
Barcode is not supported

### ISSUE THREAD

**Issue by cbrenes** [walletpass/pass-js#215]
Does the library support barcode? I saw an issue related with this it was solved but I am doing the same thing and I can't see the barcode

This is the original issue: https://github.com/destinationstransfers/passkit/issues/40

I am doing this: 
pass.barcodes([{
    message: "1234567890",
    format: 'PKBarcodeFormatQR',
    messageEncoding: 'iso-8859-1'
  }]);

@tinovyatkin @nickasd   Is this a limitation of the library or I am doing something wrong?
Library version: "@destinationstransfers/passkit": "^6.5.2"
Thanks

**Comment by tinovyatkin** [comment]
Since version of 5.x this you should either put the barcodes into a template JSON or use property setter:

```js
pass.barcodes = [
  {
    message: "1234567890",
    format: 'PKBarcodeFormatQR',
    messageEncoding: 'iso-8859-1'
  }
]
```

(If you are using VSCode then IntelliSense will help you with fields)
