### ISSUE TITLE
 Set private key in pass template before producing pass buffers

### ISSUE THREAD

**Issue by buchos92** [walletpass/pass-js#255]
Hello, I faced a fix when a "createPass" attempt shows this message:

"INFO ReferenceError: Set private key in pass template before producing pass buffers
at Pass.asBuffer (/var/task/node_modules/@walletpass/pass-js/dist/pass.js:53:19)
at createTemplate (/var/task/customers/customerAddWallet.js:67:28)"

How do I fix it?

Please any insight.

**Comment by tinovyatkin** [comment]
You need to [obtain your certificate](https://github.com/walletpass/pass-js#get-your-certificates) from Apple first, then set it to Template as [described in documentation](https://github.com/walletpass/pass-js#start-with-a-template) - i.e, either `Template.load` or `Template.setPrivateKey`

**Comment by buchos92** [comment]
I am doing the next steps:
- I am create template the way manually, like you mention
- Then "loadCertificate"
- Then add image to template, logo and icon.
- Then create Pass 
- Then, asBuffer()  

<img width="833" alt="Screen Shot 2019-10-21 at 16 11 18" src="https://user-images.githubusercontent.com/9329001/67243570-7d01a700-f41d-11e9-88b5-71570511534f.png">

**Comment by tinovyatkin** [comment]
Are you sure your certificate contains private key encrypted with `buchos` password? Did you created it according to documentation?

**Comment by buchos92** [comment]
Thanks for the help!.
Finally, I did it.
I was wrong doing  bad conversions ".p12" to ".pem", then I fixed this and the process worked.  

Regards

**Comment by pvsantosh** [comment]
Could you please tell me the correct way or commands to create .pem from .p12? I'm having the same issue.

**Comment by anija** [comment]
Same problem here. using "loadCertificate" i get the error "Set private key in pass template before producing pass buffers".

I've downloaded from Apple Identifier the certificate, open it in my keychan and then exported it as .p12.
Then i run the passkit-key command as described. It ends up creating two files: wwdr.pem and cert.pem (cert is the name of the .p12 file as well).
It's not clear which one of the file should be loaded as Certificate. And what about "private key"?

**Comment by anija** [comment]
@pvsantosh i finally managed it.
The pem file must be converted with the key or it will ask for the privateKey.

I used this command inside the key folder:
`$ openssl pkcs12 -in <cert-name>.p12 -clcerts -out signerCert.pem -passin pass:<your-password>`
Note: <your-password> is the password you typed when you exported the certificate from the KeyChain. This command will ask you to set another password you will use later.
And then i was able to load the certificate this way:
`await template.loadCertificate('<path>/signerCert.pem', <password>);`
Here you will use the password generated while converting the cert from p12 to pem.
It took me 3 different repos documentation to get this 🤦

**Comment by tomasikp** [comment]
@anija thanks for posting this. I got it to work with your openssl command.
