### ISSUE TITLE
Cutting of strip

### ISSUE THREAD

**Issue by krivochenko** [walletpass/pass-js#259]
We pack to pass strip-image of three sizes: 1125x369, 750x246 and 375x123. But on devices it is clipped on right and left.

What is a correct size? Or maybe where is no "correct" size, and width of strip depends on device.

Thanks for help.

**Comment by Dicondur** [comment]
The strip image (strip.png) is displayed behind the primary fields.

On iPhone 6 and 6 Plus The allotted space is 375 x 98 points for event tickets, 375 x 144 points for gift cards and coupons, and 375 x 123 in all other cases.

On prior hardware The allotted space is 320 x 84 points for event tickets, 320 x 110 points for other pass styles with a square barcode on devices with 3.5 inch screens, and 320 x 123 in all other cases.

Refer to this link: https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW1

**Comment by PatrickQuintal** [comment]
Images are just zipped up along with other assets. This library does not do anything to these images. I suggest you follow the above documentation or get in touch with Apple.
