### ISSUE TITLE
Pkpass file contains pass.json data in plain text

### ISSUE THREAD

**Issue by akoufatzis** [walletpass/pass-js#365]
Hello,

After opening as a text file an .pkpass file created by this library I can see some not text characters plus the data from the pass.json in plain text. Opening the same way passes I have from other vendors I don't see any plain text.

Can you please check this? Do I have to configure something in the pass creation that I have missed?

**Comment by tinovyatkin** [comment]
Do you mind attach your pass.json?

**Comment by akoufatzis** [comment]
The pass.json is as follows:
`{
	"formatVersion": 1,
	"webServiceURL": "...",
	"teamIdentifier": "...",
	"associatedStoreIdentifiers": [1266591536],
	"beacons": [
		{
			"major": 1,
			"minor": 10,
			"proximityUUID": "..."
		}
	],
	"organizationName": "...",
	"description": "...",
	"labelColor": "rgb(109, 129, 148)",
	"foregroundColor": "rgb(0, 0, 0)",
	"backgroundColor": "rgb(255, 255, 255)",
	"storeCard": {
		"primaryFields": [
			{
				"label": "",
				"key": "keepEmtpy",
				"value": ""
			}
		],
		"backFields": [
			{
				"value": "",
				"key": "explanation",
				"attributedValue": "..."
			}
		]
	}
}
`

**Comment by akoufatzis** [comment]
I found the difference between the pkpass files generated from this library and the ones generated from Apples signpass tool. This library does not compress the pkpass file (actually a zip file). It does not provide any security but why did you choose to not compress it?

**Comment by tinovyatkin** [comment]
First of all, it makes almost no sense to ZIP compress biggest files from `.pkpass` - PNG images. And second reason and that we run in resource problem with opening compressed passes with lot of PNG graphics (thinks about 3x images) on older iPhones. Those problem s disappears on passes without compression.

**Comment by akoufatzis** [comment]
Ok thanks for the information. I am closing the issue.
