### ISSUE TITLE
Encoding preventing localization importing

### ISSUE THREAD

**Issue by lucletruc** [walletpass/pass-js#368]
```
async function readStringsFromStream(stream) {
    ...
    stream.setEncoding('utf8'); // instead of stream.setEncoding('utf16le')
    ...
}
```
The current encoding in localizations.js did not work, had to change it to utf8 to properly read pass.strings files.

**Comment by tinovyatkin** [comment]
Thank you! Do you want to make a PR?

**Comment by tinovyatkin** [comment]
As per documentation `pass.strings` MUST be UTF-16 encoded. You may find some examples at `__tests__/resources/passes/Generic`.
