### ISSUE TITLE
Unable to generate barcode

### ISSUE THREAD

**Issue by nextlatam** [walletpass/pass-js#400]
I have added this:

 "barcode": {
    "message": "123456789",
    "format": "PKBarcodeFormatPDF417",
    "messageEncoding": "iso-8859-1"
  },

To my pass.json, but when it generates the pass, it doesn't show the barcode, what could be happening?

**Comment by xavism** [comment]
+1

**Comment by nextlatam** [comment]
@xavism Hello! What you have to do is use “barcodes” instead of “barcode” and also you have to use an array of barcodes as value instead of a single object, like this:

"barcodes": [{
"message": "123456789",
"format": "PKBarcodeFormatPDF417",
"messageEncoding": "iso-8859-1"
}],

I learned this by trying, this was not on the documentation of pass.js, but there were some clues at the Apple site saying that you could use multiple barcodes on a pass.

**Comment by xavism** [comment]
@nextlatam It works!, you rock thanks :)
