### ISSUE TITLE
pushUpdates seems to be broken

### ISSUE THREAD

**Issue by s-a** [walletpass/pass-js#440]
I tried to call `const res = await template.pushUpdates(deviceToken)` to send an APN which leads my app to close immediately. 

I debugged the source and when I comment out the `apn.unref();` command `pushUpdates` promise resolves. For me it feels `apn.unref();` belongs to the http2 eventhandlers where promise rejects and resolves. 

![image](https://user-images.githubusercontent.com/1270662/82436179-b377d100-9a95-11ea-911e-ba5b0392aa4c.png)

After my code change node process keeps running as the comment promises so I worked around with 
```javascript
	console.log('done')
	const res = await template.pushUpdates(deviceToken)
	console.log('done')
	template.apn.unref()
```
Very weird that `apn.unref();` acts like `process.exit()`
Can some one point me to what I am doing wrong here? Or is it a bug? 

Best regards.

**Comment by Dicondur** [comment]
Thanks @s-a!  
Only get to see the ouput when commented as above for me too!

However now I get Object: null prototype 
status :400
apns-id: 'xxxx-xxx-xx'

How shld I debug further on what this error is about?

**Comment by s-a** [comment]
You need to init template object with your public and private key. I can post some code tomorrow which works for me.

**Comment by Dicondur** [comment]
Yes, have them loaded:
Steps I followed here:

1) Hosted create card to an `URL endpoint`.
`await template.loadCertificate("pemfile","pass")`

2) Added  while creating this template:
`template.webServiceURL = "<same as deployed URL-endpoint>";`

3) The post to device register was sucessful.
Returned the apn token in the body. So the <URL-Enpoint> is pointing correctly, right?

4) Use that token to create another new template for the updated pass. 
`await template.loadCertificate("pemfile.pem","pass")`
`template.pushUpdates("the received apn token");`

This is where I get the error.
`done
[Object: null prototype] {
  ':status': 400,
  'apns-id': 'xxxx-xxx-xxxx-xxxx-xxxxxxxxxxx'
}
done`

To check new pass creation, I was able to create a new updated pass and write to a file using above. If cert issue, it shld have complainted here, right? 

Opening the new pass created in wallet also works without problem.
Dont know what 400 error is about? What would a success call look like?

Thanks!

**Comment by s-a** [comment]
Success would be status `200`. I ve created a small module at https://www.npmjs.com/package/@s-a/simple-apn. Hope this helps 👍

**Comment by Dicondur** [comment]
Yes! one step closer 🥇 now I get 200 response. 
Still no notification will try with change fields and update tags.

Thanks, much appreciate it!

**Comment by s-a** [comment]
@Dicondur did you found an alternative active apple pass module? seems this is not maintained so active.

**Comment by Dicondur** [comment]
Using https://github.com/node-apn/node-apn but still there are some similar bugs with closing the apn provider.

**Comment by AienTech** [comment]
hi there,

any updates regarding this issue? although I tried all the solutions mentioned above, I still can't send any push notifications, thus not receiving any
