### ISSUE TITLE
Problem trying to open the file event.pkpass

### ISSUE THREAD

**Issue by agarci1994** [walletpass/pass-js#505]
Hello!

I am trying to generate a passbook with the library, but the file that I generate I cannot open it from my computer, while I can open the .pkpass that you have as an example in the _test_ folder.

This is the code that I have and that ends up generating a walletPass.pkpass file: 

```
const passbook = async (req, res, next) => {

    const template = new Template("coupon", {
        passTypeIdentifier: "xxxxxxx",
        teamIdentifier: "MXL",
        backgroundColor: "red",
        sharingProhibited: true
    })

await template.loadCertificate(
    "./keys/Certificates.pem",
    "password"
);

const pass = template.createPass({
    serialNumber: "1234566661",
    description: "The best event!",
    organizationName: "Xkaee",
})

await pass.relevantDate = new Date(2020, 1, 1, 10, 0);

await pass.images.add("icon", "./passbook/event/icon.png")
await pass.images.add("logo", "./passbook/event/logo.png")

const buf = await pass.asBuffer()

await fs.writeFile("walletPass.pkpass", buf, (err) => {
       if (err) throw err;
       console.log('The file has been saved!');
   })

   
}
```
Al intentar abrirlo recibo este error: 

<img width="421" alt="Screenshot 2020-08-29 at 11 48 31" src="https://user-images.githubusercontent.com/46927442/91634043-984e2300-e9ed-11ea-999e-91c44a5f1ef3.png">

**Comment by davlis-tr** [comment]
@agarci1994 what was the issue?

**Comment by agarci1994** [comment]
the serialNumber was wrong

**Comment by ln-sergey** [comment]
> the serialNumber was wrong

How the serialNumber can be wrong?

I have the same issue, but serialNumber is just a hash string
